# Generated by Django 5.1.7 on 2025-03-27 14:28

from django.db import migrations
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]
def create_superuser(apps, schema_editor):
    from django.contrib.auth import get_user_model

    User = get_user_model()

    if User.objects.exists():
        return
    superuser = User.objects.create_superuser(
        username="superuser",
        email="example@example.com",
        password="superuser",
        last_login=timezone.now(),
    )
    superuser.save()

    operations = [
        migrations.RunPython(create_superuser),
    ]

